name: learn-github-actions
on: [push]
jobs:
  run-react-native:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - run: npm install
      - run: npx pod-install
      - run: npx react-native run-ios
